import { Outfit ,Ovo} from 'next/font/google';



import "./globals.css"; 

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit", // Add this
  display: "swap",
});


const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ovo",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="ltr" className=" scroll-smooth ">
      <body className={`${outfit.variable} ${ovo.variable} antialiased leading-8 overflow-x-hidden `}>
        {/* dark:bg-[#11001F] dark:text-white */}
        {children}
      </body>
    </html>
  );
}
